### ISSUE TITLE
Docs CRs

### ISSUE THREAD

**Issue by steve0xp** [balancer/scaffold-balancer-v3#17]
## Scope

This issue encompasses possible docs change requests (CRs). It is a live issue. It is also a referencable note to help create said CRs to the docs when we have time. If the ideas here are worthwhile, we will open issues and respective PR(s) to make the changes in the docs.

Ref: [BalancerV3 Docs](https://docs-v3.balancer.fi/)

**Comment by t-phoenix** [comment]
Deployment steps for Core System Contract
Scaffold-balancer-v3 is seamless in providing playground dev experience with balancer v3 pools, but it lacks in providing steps to replicate the necessary deployment process for core system contracts like vault, Router,  permit2, extensions, etc.

Specially with vaultFactory overexceeding smart-contract size limit, it becomes really difficult to deploy core smart-contracts.

**Comment by MattPereira** [comment]
Hey @t-phoenix 
The scope for scaffold is to focus on helping devs create v3 pools and hooks

Not sure what plan is for supporting deployment of v3 core contracts, but feel free to ask [on our discord dev support channel](https://discord.com/channels/638460494168064021/638465986839707660)

**Comment by MattPereira** [comment]
Cleaning up outdated issue
