### ISSUE TITLE
Improve CI Checks

### ISSUE THREAD

**Issue by MattPereira** [balancer/scaffold-balancer-v3#55]
### Overview
I couldn't figure out deploying contracts to an anvil fork as part of the CI checks in #53. The `yarn fork` command executes successfully to start an anvil fork of sepolia as part of the GHA, but it would hang indefinitely instead of moving on to the next step to deploy the contracts

**Comment by johngrantuk** [comment]
I remember I had a similar issue a long time ago - I think I needed to add ampersand at the end of the command, so try: `yarn fork &`

**Comment by brunoguerios** [comment]
True! That's how it's setup on the [old SDK](https://github.com/balancer/balancer-sdk/blob/ba9480fc7978a02a84dee4f6d272690cc11a1b6e/.github/workflows/balancer-js.yaml#L86)
