### ISSUE TITLE
bug: Not able to deploy contract

### ISSUE THREAD

**Issue by 2facedsquid** [balancer/scaffold-balancer-v3#67]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

git clone

### Current Behavior

contracts dont deploy, the issue is with some changes of IERC20 to address that veBAL needs to be casted to IER20(veBAL) in  packages/foundry/script/02_DeployConstantProduct.s.sol

### Expected Behavior

contracts should deploy

### Steps To Reproduce

yarn deploy

### Anything else?

Error:
Compiler run failed:
Error (9553): Invalid type for argument in function call. Invalid implicit conversion from address to contract IERC20 requested.
  --> script/02_DeployConstantProduct.s.sol:44:13:
   |
44 |             veBAL
   |             ^^^^^

**Comment by MattPereira** [comment]
merged #68
