### ISSUE TITLE
bug: Yarn Install Failure: Package Caching and Build Errors

### ISSUE THREAD

**Issue by onyedikachi-david** [balancer/scaffold-balancer-v3#85]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

git clone

## Description

When attempting to run 'yarn install' in a project that depends on the `forge-gas-snapshot` package, the installation fails due to an error in the `package.json` file of the `forge-gas-snapshot` package. The error message indicates that the package name contains illegal characters.

## Error Details

yarn install
! Corepack is about to download https://repo.yarnpkg.com/3.2.3/packages/yarnpkg-cli/bin/yarn.js
? Do you want to continue? [Y/n] y
➤ YN0065: Yarn will periodically gather anonymous telemetry: https://yarnpkg.com/advanced/telemetry
➤ YN0065: Run yarn config set --home enableTelemetry 0 to disable
➤ YN0000: ┌ Resolution step
[...]
➤ YN0000: ┌ Fetch step
➤ YN0058: │ forge-gas-snapshot@https://github.com/ylv-io/forge-gas-snapshot.git#commit=ee8e1f02009785ab81a5058a18c75d5d3b7a894d: Packing the package failed (exit code 1, logs can be found here: /private/var/folders/s8/s42sth591gz3yyslqdj95ynm0000gn/T/xfs-420ded74/pack.log)
➤ YN0000: └ Completed in 1m 3s
➤ YN0000: Failed with errors in 1m 3s
pack.log content:
Packing forge-gas-snapshot@https://github.com/ylv-io/forge-gas-snapshot.git#commit=ee8e1f02009785ab81a5058a18c75d5d3b7a894d from sources
No package manager configuration detected; defaulting to Yarn
yarn pack v1.22.22
error package.json: Name contains illegal characters
info Visit https://yarnpkg.com/en/docs/cli/pack for documentation about this command.

## Expected Behavior

The `yarn install` command should complete successfully, installing all dependencies and building the necessary packages.

## Steps to Reproduce

1. Clone the repository [(scaffold-balancer-v3)
](https://github.com/balancer/scaffold-balancer-v3)2. Run `yarn install`

### Anything else?

Logs:

Packing forge-gas-snapshot@https://github.com/ylv-io/forge-gas-snapshot.git#commit=ee8e1f02009785ab81a5058a18c75d5d3b7a894d from sources
No package manager configuration detected; defaulting to Yarn

! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e.
! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager

yarn pack v1.22.22
error package.json: Name contains illegal characters
info Visit https://yarnpkg.com/en/docs/cli/pack for documentation about this command.

**Comment by MattPereira** [comment]
Hey @onyedikachi-david thanks for the excellently detailed bug report :pray: 

unfortunately, you're the first to run into this and i'm unable to recreate so it's pretty difficult for me to offer a solution

definitely recommend attacking this one with AI prompts

here are some guesses:
- run `yarn cache clean`
- try upgrading your version of yarn to 2.x or 3.x
- delete the `"forge-gas-snapshot"` dependency from `packages/foundry/package.json` and see if you can run w/o it
- delete the `yarn.lock` file

**Comment by onyedikachi-david** [comment]
Thank you, I'll try those. Interestingly, It worked well on Gitpod, the error was on my M1 Mac book air.

**Comment by onyedikachi-david** [comment]
Finally Had it working using this steps:

```shell
> nvm --version
0.40.1
> node --version
v22.8.0
> yarn --version
3.2.3
> nvm install node --latest-npm && nvm use node
Downloading and installing node v22.9.0...
Downloading https://nodejs.org/dist/v22.9.0/node-v22.9.0-darwin-arm64.tar.xz...
########################################################################################################################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v22.9.0 (npm v10.8.3)
Now using node v22.9.0 (npm v10.8.3)
> corepack prepare yarn@stable --activate
Preparing yarn@stable for immediate activation...
> yarn set version stable
zsh: command not found: yarn
> corepack enable
> corepack prepare yarn@stable --activate
Preparing yarn@stable for immediate activation...
> yarn set version stable
➤ YN0000: Retrieving https://repo.yarnpkg.com/4.5.0/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-4.5.0.cjs
➤ YN0000: Done in 0s 852ms
> yarn --version
4.5.0
```
